# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ryan Thomas Foundation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It is our mission in to continue to raise awareness of the dangers around water, both to children and adults, 
  while hosting fundraising events that will contribute to a decrease in local water related fatalities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://theryanthomasfoundation.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

golf_closed: true
total_contributions: '150,000'
lifejackets_donated: 725
